name: videosync
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pandas=2.2.2
  - numpy=1.26.4
  - matplotlib=3.8.4
  - black=24.4.0
  - opencv=4.9.0
  - tqdm=4.66.2
  - scipy=1.13.0
  - scp=0.15.0
  - moviepy=1.0.3
  - pyyaml=6.0.2
  - pyinstaller=6.10.0
  - soundfile=0.13.0
  - pip
  - pip:
      - git+ssh://git@github.com/BCM-Neurosurgery/Python-Utilities-videosync.git
