# Camera serial number
# Refer to README for available camera serial numbers
# Has to be a list of one or multiple camera serial numbers
cam_serial: ["23512014"]

# Absolute paths to stitched directory and camera recording directory
# The stitched directory contains the stitched NSP files
# The camera recording directory contains date folders with camera recordings
# On Linux, use single forward slashes as shown below
# On Windows, use double backslashes e.g. "C:\\Users\\user\\Desktop\\data"
nsp_dir: "/mnt/lake-database/stitched/YFK/EMU-0036_urge"
cam_recording_dir: "/mnt/datalake/data/emu/YFKDatafile/VIDEO"

# Paths for the output files
# Subdirectories will be created in the output directory named after the camera serial number
# The output files will be saved in the respective subdirectories
output_dir: "/home/auto/CODE/utils/video-sync/Testing/YFKTesting"

# Channel name for the audio data
# Do not change this
channel_name: "RoomMic2"
