site_name: Video Sync
repo_url: https://github.com/BCM-Neurosurgery/video-sync
repo_name: BCM-Neurosurgery/video-sync


theme:
  name: material
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.suggest
    - content.tabs.link


nav:
  - Home: index.md
  - Installation: installation.md
  - Configuration: configuration.md
  - Usage: usage.md
  - Features: features.md
  - EMU Camera Serials: emu-cameras.md
  - License: license.md
  - Developer Guide:
      - Overview: developer-guide/index.md
      - Program Flow: developer-guide/program-flow.md
      - Contributing: developer-guide/contributing.md
  - API Reference:
      - Overview: api/index.md
      - DataPool: api/datapool.md
      - Nev: api/nev.md
      - Nsx: api/nsx.md
      - Video: api/video.md
      - Videojson: api/videojson.md
      - Pathutils: api/pathutils.md
      - Utils: api/utils.md
  - Understanding Anomalies:
      - Discontinuity in JSON: understanding-anomalies/discontinuity-in-json.md
      - Discontinuity in Nev: understanding-anomalies/discontinuity-in-nev.md
      - JSON Timestamp Anomalies: understanding-anomalies/json-diff-timestamp.md
  - Understanding Data:
      - Understanding Nev: understanding-data/understanding-nev.md
      - Understanding Ns5: understanding-data/understanding-ns5.md
      - Understanding JSON: understanding-data/understanding-json.md

plugins:
  - search
  - table-reader
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            show_signature_annotations: true
            members_order: alphabetical

markdown_extensions:
  - toc:
      permalink: true
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/BCM-Neurosurgery/video-sync
